AWSTemplateFormatVersion: '2010-09-09'
Description: Sample function using multiple layers to require BS4 and LXML in Python
  3.6
Resources:
  bs4Layer:
    Properties:
      CompatibleRuntimes:
      - python3.6
      ContentUri: s3://sbryen-sam/a4d78c35c3c2d44ffba37f65ac4a3ea4
      Description: Beautiful Soup 4 Layer for Python 3.6
      LayerName: bs4-python36
      RetentionPolicy: Retain
    Type: AWS::Serverless::LayerVersion
  getEvangelistsFunction:
    Properties:
      CodeUri: s3://sbryen-sam/02532786fc6d24e358011b5a167bc008
      Description: A function to get evangelist headshots and log gender/age about
        each.
      Handler: lambda_function.lambda_handler
      Layers:
      - Ref: bs4Layer
      MemorySize: 128
      Policies:
      - RekognitionDetectOnlyPolicy: {}
      Runtime: python3.6
      Timeout: 30
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
